/* ============================================
   0xFolio - Portfolio Interactions
   Modal, smooth scroll, accessibility
   ============================================ */

// ===== Project Data =====
const projects = [
  {
    id: "project1",
    title: "Neural Path Planning for Autonomous Drones",
    year: "2025",
    links: [
      { label: "View on GitHub", url: "https://github.com" },
      { label: "Read Paper", url: "https://arxiv.org" }
    ],
    abstract: "This research presents a novel neural network architecture for real-time path planning in autonomous drone systems operating in unstructured environments. The proposed method combines a convolutional encoder for visual scene understanding with a transformer-based decoder for sequential path generation. Trained on over 50,000 simulated flight hours across diverse environments including forests, urban canyons, and indoor spaces, the model achieves 94.2% collision-free navigation while reducing computational latency by 60% compared to traditional RRT* algorithms. The system was validated on a fleet of custom-built quadrotors equipped with stereo vision cameras and onboard NVIDIA Jetson processors.",
    sections: [
      {
        title: "Demonstration Video",
        description: "Watch the drone navigate through a dense forest environment in real-time using only onboard visual sensing and the neural path planner. The system processes camera frames at 30 FPS and generates collision-free trajectories with a latency under 50ms.",
        media: "images/project1-demo.jpg",
        mediaAlt: "Drone demonstration navigating through forest at golden hour"
      },
      {
        title: "Architecture",
        description: "The system uses a two-stage pipeline: (1) a ResNet-50 backbone extracts spatial features from stereo camera inputs, (2) a 6-layer transformer decoder attends to these features and outputs a sequence of waypoints. The model is trained end-to-end using imitation learning from expert trajectories generated by an RRT* planner with full environment knowledge.",
        media: null
      }
    ]
  },
  {
    id: "project2",
    title: "Distributed Log Analytics Platform",
    year: "2024",
    links: [
      { label: "View on GitHub", url: "https://github.com" },
      { label: "Live Demo", url: "https://demo.example.com" }
    ],
    abstract: "A horizontally distributed log processing platform capable of ingesting and analyzing over 2 million events per second with sub-second query latency. Built on a custom stream processing engine that combines the best of Apache Flink and ClickHouse architectures, the system provides real-time anomaly detection, pattern recognition, and automated alerting for enterprise infrastructure monitoring. The platform reduced incident response time by 75% at a Fortune 500 deployment and operates on commodity hardware clusters.",
    sections: [
      {
        title: "System Overview",
        description: "The platform ingests logs from thousands of microservices through a custom Kafka-like message broker, processes them through a DAG-based computation graph, and stores aggregated results in a columnar database optimized for time-series queries.",
        media: "images/project2-demo.jpg",
        mediaAlt: "Real-time analytics dashboard with system metrics and network topology"
      },
      {
        title: "Results",
        description: "Deployed across 12 availability zones processing 50TB of log data daily. Query latency p99 < 200ms. Achieved 99.999% uptime over 6 months of production operation.",
        media: null
      }
    ]
  },
  {
    id: "project3",
    title: "Real-time Collaboration Engine",
    year: "2024",
    links: [
      { label: "View on GitHub", url: "https://github.com" }
    ],
    abstract: "A conflict-free replicated data type (CRDT) based collaboration engine supporting real-time document editing with offline-first capabilities. The system handles concurrent edits from thousands of users with guaranteed eventual consistency and zero merge conflicts. Built in Rust and compiled to WebAssembly for browser deployment, achieving 60fps synchronization even on low-bandwidth connections.",
    sections: [
      {
        title: "Demo",
        description: "The engine powers a Notion-like document editor where multiple users can simultaneously edit text, tables, and embedded components without any locking mechanisms.",
        media: "images/project3-demo.jpg",
        mediaAlt: "Collaborative editor interface showing multiple user cursors editing simultaneously"
      }
    ]
  },
  {
    id: "project4",
    title: "Low-latency Trading Infrastructure",
    year: "2023",
    links: [
      { label: "View on GitHub", url: "https://github.com" },
      { label: "Read Paper", url: "https://arxiv.org" }
    ],
    abstract: "A high-frequency trading infrastructure built from the ground up with a custom kernel-bypass networking stack and lock-free data structures. The system achieves sub-microsecond round-trip latency for market data ingestion and order execution, making it competitive with industry-leading solutions at a fraction of the cost.",
    sections: [
      {
        title: "Performance",
        description: "Benchmarked at 850 nanoseconds median RTT on a 10Gbps network. Handles 5 million orders per second on a single server with zero packet loss during burst traffic.",
        media: null
      }
    ]
  }
];

// ===== DOM Elements =====
const modal = document.getElementById("project-modal");
const modalContent = document.getElementById("modal-content");
const modalCloseBtn = modal.querySelector(".modal__close");
const projectCards = document.querySelectorAll(".project-card");

let lastFocusedElement = null;

// ===== Modal Functions =====

function openModal(projectId) {
  const project = projects.find(p => p.id === projectId);
  if (!project) return;

  // Store last focused element for restoration
  lastFocusedElement = document.activeElement;

  // Populate modal content
  modalContent.innerHTML = buildModalHTML(project);

  // Show modal
  modal.setAttribute("aria-hidden", "false");
  modal.classList.add("modal--open");
  document.body.style.overflow = "hidden";

  // Focus close button for accessibility
  setTimeout(() => {
    modalCloseBtn.focus();
  }, 100);
}

function closeModal() {
  modal.classList.remove("modal--open");
  modal.setAttribute("aria-hidden", "true");
  document.body.style.overflow = "";

  // Restore focus
  if (lastFocusedElement) {
    lastFocusedElement.focus();
    lastFocusedElement = null;
  }
}

function buildModalHTML(project) {
  let linksHTML = "";
  if (project.links && project.links.length > 0) {
    linksHTML = `
      <div class="modal__links">
        ${project.links.map(link => `
          <a href="${link.url}" class="btn btn--filled" target="_blank" rel="noopener noreferrer">${link.label}</a>
        `).join("")}
      </div>
    `;
  }

  let sectionsHTML = "";
  if (project.sections && project.sections.length > 0) {
    sectionsHTML = project.sections.map(section => `
      <div class="modal__section">
        <h3 class="modal__section-title">${section.title}</h3>
        <p class="modal__text">${section.description}</p>
        ${section.media ? `<img src="${section.media}" alt="${section.mediaAlt || ""}" class="modal__media" loading="lazy">` : ""}
      </div>
    `).join("");
  }

  return `
    <h2 class="modal__title" id="modal-title">${project.title}</h2>
    <div class="modal__meta">
      <div>
        <span class="modal__year-label">Year</span>
        <span class="modal__year-value">${project.year}</span>
      </div>
      ${linksHTML}
    </div>
    <div class="modal__section">
      <h3 class="modal__section-title">Abstract</h3>
      <p class="modal__text">${project.abstract}</p>
    </div>
    ${sectionsHTML}
  `;
}

// ===== Event Listeners =====

// Project card click
projectCards.forEach(card => {
  card.addEventListener("click", () => {
    const projectId = card.getAttribute("data-project");
    openModal(projectId);
  });

  // Keyboard support
  card.addEventListener("keydown", (e) => {
    if (e.key === "Enter" || e.key === " ") {
      e.preventDefault();
      const projectId = card.getAttribute("data-project");
      openModal(projectId);
    }
  });
});

// Close button
modalCloseBtn.addEventListener("click", closeModal);

// Click on backdrop to close
modal.addEventListener("click", (e) => {
  if (e.target === modal) {
    closeModal();
  }
});

// Escape key to close
document.addEventListener("keydown", (e) => {
  if (e.key === "Escape" && modal.classList.contains("modal--open")) {
    closeModal();
  }
});

// Focus trap within modal
modal.addEventListener("keydown", (e) => {
  if (e.key !== "Tab") return;

  const focusableElements = modal.querySelectorAll(
    'a[href], button, textarea, input[type="text"], input[type="radio"], input[type="checkbox"], select'
  );

  if (focusableElements.length === 0) return;

  const firstElement = focusableElements[0];
  const lastElement = focusableElements[focusableElements.length - 1];

  if (e.shiftKey) {
    if (document.activeElement === firstElement) {
      e.preventDefault();
      lastElement.focus();
    }
  } else {
    if (document.activeElement === lastElement) {
      e.preventDefault();
      firstElement.focus();
    }
  }
});

// ===== Smooth Scroll for Navigation =====
document.querySelectorAll('.nav__link[href^="#"]').forEach(anchor => {
  anchor.addEventListener("click", function(e) {
    e.preventDefault();
    const targetId = this.getAttribute("href");
    const targetElement = document.querySelector(targetId);
    if (targetElement) {
      targetElement.scrollIntoView({
        behavior: "smooth",
        block: "start"
      });
    }
  });
});

// ===== Active Navigation State on Scroll =====
const sections = document.querySelectorAll("[id]");
const navLinks = document.querySelectorAll(".nav__link");

function updateActiveNav() {
  let current = "";
  sections.forEach(section => {
    const sectionTop = section.offsetTop;
    if (scrollY >= sectionTop - 200) {
      current = section.getAttribute("id");
    }
  });

  navLinks.forEach(link => {
    link.classList.remove("nav__link--active");
    if (link.getAttribute("href") === `#${current}`) {
      link.classList.add("nav__link--active");
    }
  });
}

window.addEventListener("scroll", updateActiveNav);
